#pragma once

#include "visit/visitor.h"
#include "parse/ast.h"

#include "codegen/context.h"
#include "codegen/codegen.h"

class GlobalsAssembler : public ASTVisitor
{
public:
    GlobalsAssembler(CodeGenContext &con, CodeGen &codeGen);

    // GLOBALS METHODS START

// The following code was autogenerated - see the utils/ directory
void visitAdd(ASTNS::Add *ast) override;
void visitMult(ASTNS::Mult *ast) override;
void visitNew_expr(ASTNS::New_expr *ast) override;
void visitNew_stmt(ASTNS::New_stmt *ast) override;
void visitPrimary(ASTNS::Primary *ast) override;
void visitUnary(ASTNS::Unary *ast) override;
// This code was autogenerated - see the utils/ directory

    // GLOBALS METHODS END
    
private:
    CodeGenContext &context;
    CodeGen &codeGen;
};
