#pragma once

#include "ast/ast.h"

#include "llvm/Support/raw_ostream.h"

namespace ASTNS
{
    class PrintVisitor :
        public ASTNS::DeclB::Visitor,
        public ASTNS::ArgB::Visitor,
        public ASTNS::StmtB::Visitor,
        public ASTNS::ExprB::Visitor,
        public ASTNS::VStmtIB::Visitor,
        public ASTNS::PListB::Visitor,
        public ASTNS::TypeB::Visitor,
        public ASTNS::CUB::Visitor,
        public ASTNS::LineEndingB::Visitor
    {
    public:
        PrintVisitor(llvm::raw_ostream &ostream);
        // PRINTVISIT METHODS START

// The following code was autogenerated - see the utils/ directory
void visitAdditionExpr(ASTNS::AdditionExpr *ast) override;
void visitArg(ASTNS::Arg *ast) override;
void visitArgList(ASTNS::ArgList *ast) override;
void visitArgList_OPT(ASTNS::ArgList_OPT *ast) override;
void visitArgSegment(ASTNS::ArgSegment *ast) override;
void visitAssignmentExpr(ASTNS::AssignmentExpr *ast) override;
void visitBinAndExpr(ASTNS::BinAndExpr *ast) override;
void visitBinOrExpr(ASTNS::BinOrExpr *ast) override;
void visitBitAndExpr(ASTNS::BitAndExpr *ast) override;
void visitBitOrExpr(ASTNS::BitOrExpr *ast) override;
void visitBitShiftExpr(ASTNS::BitShiftExpr *ast) override;
void visitBitXorExpr(ASTNS::BitXorExpr *ast) override;
void visitBracedBlock(ASTNS::BracedBlock *ast) override;
void visitBuiltinType(ASTNS::BuiltinType *ast) override;
void visitCU(ASTNS::CU *ast) override;
void visitCallExpr(ASTNS::CallExpr *ast) override;
void visitCastExpr(ASTNS::CastExpr *ast) override;
void visitCompEQExpr(ASTNS::CompEQExpr *ast) override;
void visitCompLGTExpr(ASTNS::CompLGTExpr *ast) override;
void visitDeclList(ASTNS::DeclList *ast) override;
void visitExprStmt(ASTNS::ExprStmt *ast) override;
void visitExpr_OPT(ASTNS::Expr_OPT *ast) override;
void visitForExpr(ASTNS::ForExpr *ast) override;
void visitFunctionDecl(ASTNS::FunctionDecl *ast) override;
void visitIfExpr(ASTNS::IfExpr *ast) override;
void visitImplRet(ASTNS::ImplRet *ast) override;
void visitImplRet_OPT(ASTNS::ImplRet_OPT *ast) override;
void visitIndentedBlock(ASTNS::IndentedBlock *ast) override;
void visitLineEnding(ASTNS::LineEnding *ast) override;
void visitLineEnding_OPT(ASTNS::LineEnding_OPT *ast) override;
void visitMultExpr(ASTNS::MultExpr *ast) override;
void visitParam(ASTNS::Param *ast) override;
void visitParamList(ASTNS::ParamList *ast) override;
void visitParamList_OPT(ASTNS::ParamList_OPT *ast) override;
void visitParamSegment(ASTNS::ParamSegment *ast) override;
void visitPrimaryExpr(ASTNS::PrimaryExpr *ast) override;
void visitRetStmt(ASTNS::RetStmt *ast) override;
void visitStmtList(ASTNS::StmtList *ast) override;
void visitStmtList_OPT(ASTNS::StmtList_OPT *ast) override;
void visitUnaryExpr(ASTNS::UnaryExpr *ast) override;
void visitVarStmt(ASTNS::VarStmt *ast) override;
void visitVarStmtItem(ASTNS::VarStmtItem *ast) override;
void visitVarStmtItemList(ASTNS::VarStmtItemList *ast) override;
void visitVarStmtItemSegment(ASTNS::VarStmtItemSegment *ast) override;
void visitVarStmt_OPT(ASTNS::VarStmt_OPT *ast) override;
// This code was autogenerated - see the utils/ directory

        // PRINTVISIT METHODS END

    private:
        int indent;
        bool pindent;
        // short for print at indent
        void pai(std::string &s);
        void pai(std::string &&s);

        llvm::raw_ostream &ostream;
    };
}
