name: brace
version: 0.0.0
maintainer: Jason Nguyen <lsotnnirhcdfkb@gmail.com>
github: lsotnnirhcdfkb/brace

ghc-options: -Wall -O0

default-extensions:
  - LambdaCase

dependencies:
  - base
  - ansi-terminal
  - mtl
  - containers
  - template-haskell

internal-libraries:
  brace-internal:
    source-dirs:
      - src

    dependencies:
      - brace-test-lib

  brace-test-lib:
    source-dirs:
      - test

executable:
  main: src/Main.hs

  dependencies:
    - brace-internal
    - brace-test-lib

tests:
  brace-test:
    main: test/test.hs

    dependencies:
      - brace-internal
      - brace-test-lib
