#include "ast/printvisitor.h"
#include "ast/ast.h"

#include "utils/format.h"

#include <iostream>
#include <string>

template <typename T>
static void printField(ASTNS::PrintVisitor &p, std::unique_ptr<T> &ast) {
    if (ast)
        ast->accept(p);
    else
        p.pai("nullptr\n");
}
template <typename T>
static void printField(ASTNS::PrintVisitor &p, std::vector<std::unique_ptr<T>> &v) {
    p.pai("[\n");
    ++p.indent;
    for (std::unique_ptr<T> &a : v)
        a->accept(p);
    --p.indent;
    p.pai("]\n");
}
static void printField(ASTNS::PrintVisitor &p, Token const &t) {
    p.pai("\"");
    p.pai(t.stringify());
    p.pai("\"\n");
}
static void printField(ASTNS::PrintVisitor &p, int i) {
    p.pai(std::to_string(i));
    p.pai("\n");
}
static void printField(ASTNS::PrintVisitor &p, bool i) {
    p.pai(i ? "true" : "false");
    p.pai("\n");
}
static void printField(ASTNS::PrintVisitor &p, std::vector<Token> &v) {
    p.pai("[");
    bool first = true;
    for (Token const &t : v) {
        if (!first)
            p.pai(", ");
        p.pai("\"");
        p.pai(t.stringify());
        p.pai("\"");

        first = false;
    }
    p.pai("]\n");
}
static void printField(ASTNS::PrintVisitor &p, Maybe<Location const> const &l) {
    p.pai(format("<maybe location: {}>\n", l.has()));
}

// PRINTVISITOR START
// The following code was autogenerated - see the utils/ directory
void ASTNS::PrintVisitor::visit_decl_list(ASTNS::DeclList &a) {
    pai("DeclList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<Decl>> decls = ");
    printField(*this, a.decls);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_stmt_list(ASTNS::StmtList &a) {
    pai("StmtList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<Stmt>> stmts = ");
    printField(*this, a.stmts);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_param_list(ASTNS::ParamList &a) {
    pai("ParamList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<ParamB>> params = ");
    printField(*this, a.params);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_arg_list(ASTNS::ArgList &a) {
    pai("ArgList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<Arg>> args = ");
    printField(*this, a.args);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_var_stmt_item_list(ASTNS::VarStmtItemList &a) {
    pai("VarStmtItemList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<VarStmtItem>> items = ");
    printField(*this, a.items);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_impl_member_list(ASTNS::ImplMemberList &a) {
    pai("ImplMemberList {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<ImplMember>> members = ");
    printField(*this, a.members);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_pure_location(ASTNS::PureLocation &a) {
    pai("PureLocation {\n");
    ++indent;
    pai("int dummy = ");
    printField(*this, a.dummy);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_implicit_decl(ASTNS::ImplicitDecl &a) {
    pai("ImplicitDecl {\n");
    ++indent;
    pai("int dummy = ");
    printField(*this, a.dummy);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_cu(ASTNS::CU &a) {
    pai("CU {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<Decl>> decls = ");
    printField(*this, a.decls);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_impl_decl(ASTNS::ImplDecl &a) {
    pai("ImplDecl {\n");
    ++indent;
    pai("std::unique_ptr<Type> implFor = ");
    printField(*this, a.implFor);
    pai("std::vector<std::unique_ptr<ImplMember>> members = ");
    printField(*this, a.members);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_function_decl(ASTNS::FunctionDecl &a) {
    pai("FunctionDecl {\n");
    ++indent;
    pai("std::unique_ptr<Type> retty = ");
    printField(*this, a.retty);
    pai("Token name = ");
    printField(*this, a.name);
    pai("std::vector<std::unique_ptr<ParamB>> params = ");
    printField(*this, a.params);
    pai("std::unique_ptr<Block> body = ");
    printField(*this, a.body);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_function_impl_member(ASTNS::FunctionImplMember &a) {
    pai("FunctionImplMember {\n");
    ++indent;
    pai("std::unique_ptr<FunctionDecl> fun = ");
    printField(*this, a.fun);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_var_stmt(ASTNS::VarStmt &a) {
    pai("VarStmt {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<VarStmtItem>> items = ");
    printField(*this, a.items);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_var_stmt_item(ASTNS::VarStmtItem &a) {
    pai("VarStmtItem {\n");
    ++indent;
    pai("std::unique_ptr<Type> type = ");
    printField(*this, a.type);
    pai("bool mut = ");
    printField(*this, a.mut);
    pai("Token name = ");
    printField(*this, a.name);
    pai("Token equal = ");
    printField(*this, a.equal);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_expr_stmt(ASTNS::ExprStmt &a) {
    pai("ExprStmt {\n");
    ++indent;
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    pai("bool suppress = ");
    printField(*this, a.suppress);
    pai("Maybe<Location const> dot = ");
    printField(*this, a.dot);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_ret_stmt(ASTNS::RetStmt &a) {
    pai("RetStmt {\n");
    ++indent;
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_path_type(ASTNS::PathType &a) {
    pai("PathType {\n");
    ++indent;
    pai("std::unique_ptr<Path> path = ");
    printField(*this, a.path);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_pointer_type(ASTNS::PointerType &a) {
    pai("PointerType {\n");
    ++indent;
    pai("bool mut = ");
    printField(*this, a.mut);
    pai("std::unique_ptr<Type> type = ");
    printField(*this, a.type);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_this_type(ASTNS::ThisType &a) {
    pai("ThisType {\n");
    ++indent;
    pai("Token th = ");
    printField(*this, a.th);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_arg(ASTNS::Arg &a) {
    pai("Arg {\n");
    ++indent;
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_param(ASTNS::Param &a) {
    pai("Param {\n");
    ++indent;
    pai("std::unique_ptr<Type> type = ");
    printField(*this, a.type);
    pai("Token name = ");
    printField(*this, a.name);
    pai("bool mut = ");
    printField(*this, a.mut);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_this_param(ASTNS::ThisParam &a) {
    pai("ThisParam {\n");
    ++indent;
    pai("bool ptr = ");
    printField(*this, a.ptr);
    pai("bool mut = ");
    printField(*this, a.mut);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_block(ASTNS::Block &a) {
    pai("Block {\n");
    ++indent;
    pai("std::vector<std::unique_ptr<Stmt>> stmts = ");
    printField(*this, a.stmts);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_if_expr(ASTNS::IfExpr &a) {
    pai("IfExpr {\n");
    ++indent;
    pai("Token iftok = ");
    printField(*this, a.iftok);
    pai("Token elsetok = ");
    printField(*this, a.elsetok);
    pai("std::unique_ptr<Expr> cond = ");
    printField(*this, a.cond);
    pai("std::unique_ptr<Expr> trues = ");
    printField(*this, a.trues);
    pai("std::unique_ptr<Expr> falses = ");
    printField(*this, a.falses);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_while_expr(ASTNS::WhileExpr &a) {
    pai("WhileExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> cond = ");
    printField(*this, a.cond);
    pai("std::unique_ptr<Expr> body = ");
    printField(*this, a.body);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_assignment_expr(ASTNS::AssignmentExpr &a) {
    pai("AssignmentExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> target = ");
    printField(*this, a.target);
    pai("Token equal = ");
    printField(*this, a.equal);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_short_circuit_expr(ASTNS::ShortCircuitExpr &a) {
    pai("ShortCircuitExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> lhs = ");
    printField(*this, a.lhs);
    pai("Token op = ");
    printField(*this, a.op);
    pai("std::unique_ptr<Expr> rhs = ");
    printField(*this, a.rhs);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_binary_expr(ASTNS::BinaryExpr &a) {
    pai("BinaryExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> lhs = ");
    printField(*this, a.lhs);
    pai("Token op = ");
    printField(*this, a.op);
    pai("std::unique_ptr<Expr> rhs = ");
    printField(*this, a.rhs);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_cast_expr(ASTNS::CastExpr &a) {
    pai("CastExpr {\n");
    ++indent;
    pai("std::unique_ptr<Type> type = ");
    printField(*this, a.type);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_unary_expr(ASTNS::UnaryExpr &a) {
    pai("UnaryExpr {\n");
    ++indent;
    pai("Token op = ");
    printField(*this, a.op);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_addrof_expr(ASTNS::AddrofExpr &a) {
    pai("AddrofExpr {\n");
    ++indent;
    pai("Token op = ");
    printField(*this, a.op);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    pai("bool mut = ");
    printField(*this, a.mut);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_deref_expr(ASTNS::DerefExpr &a) {
    pai("DerefExpr {\n");
    ++indent;
    pai("Token op = ");
    printField(*this, a.op);
    pai("std::unique_ptr<Expr> expr = ");
    printField(*this, a.expr);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_call_expr(ASTNS::CallExpr &a) {
    pai("CallExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> callee = ");
    printField(*this, a.callee);
    pai("Token oparn = ");
    printField(*this, a.oparn);
    pai("std::vector<std::unique_ptr<Arg>> args = ");
    printField(*this, a.args);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_field_access_expr(ASTNS::FieldAccessExpr &a) {
    pai("FieldAccessExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> operand = ");
    printField(*this, a.operand);
    pai("Token dot = ");
    printField(*this, a.dot);
    pai("Token field = ");
    printField(*this, a.field);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_method_call_expr(ASTNS::MethodCallExpr &a) {
    pai("MethodCallExpr {\n");
    ++indent;
    pai("std::unique_ptr<Expr> operand = ");
    printField(*this, a.operand);
    pai("Token dot = ");
    printField(*this, a.dot);
    pai("Token method = ");
    printField(*this, a.method);
    pai("Token oparn = ");
    printField(*this, a.oparn);
    pai("std::vector<std::unique_ptr<Arg>> args = ");
    printField(*this, a.args);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_primary_expr(ASTNS::PrimaryExpr &a) {
    pai("PrimaryExpr {\n");
    ++indent;
    pai("Token value = ");
    printField(*this, a.value);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_path_expr(ASTNS::PathExpr &a) {
    pai("PathExpr {\n");
    ++indent;
    pai("std::unique_ptr<Path> path = ");
    printField(*this, a.path);
    --indent;
    pai("}\n");
}
void ASTNS::PrintVisitor::visit_path(ASTNS::Path &a) {
    pai("Path {\n");
    ++indent;
    pai("std::vector<Token> segments = ");
    printField(*this, a.segments);
    --indent;
    pai("}\n");
}
// This code was autogenerated - see the utils/ directory
// PRINTVISITOR END

void ASTNS::PrintVisitor::pai(std::string const &s) {
    for (auto i = s.begin(); i != s.end(); ++i) {
        if (pindent)
            for (int j = 0; j < indent; ++j)
                ostream << "    ";

        pindent = false;
        ostream << *i;

        if (*i == '\n')
            pindent = true;
    }
}

ASTNS::PrintVisitor::PrintVisitor(llvm::raw_ostream &ostream): indent(0), ostream(ostream) {}
