#pragma once

#include <memory>
#include <vector>
#include "lex/token.h"
#include "visit/visitor.h"

namespace ASTNS
{
// ASTHEADER START

// The following code was autogenerated - see the utils/ directory
    class AST;
    class ArgB;
    class DeclB;
    class ExprB;
    class PListB;
    class StmtB;
    class TypeB;
    class VStmtIB;
    class AdditionExpr;
    class Arg;
    class ArgList;
    class AssignmentExpr;
    class BinandExpr;
    class BinnotExpr;
    class BinorExpr;
    class BitandExpr;
    class BitorExpr;
    class BitshiftExpr;
    class BitxorExpr;
    class Block;
    class BuiltinType;
    class CallExpr;
    class CompeqExpr;
    class ComplgtExpr;
    class Decl;
    class DeclList;
    class EmptyStmt;
    class Expr;
    class ExprStmt;
    class Function;
    class MultExpr;
    class Param;
    class ParamList;
    class PrimaryExpr;
    class RetStmt;
    class Stmt;
    class StmtList;
    class TernaryExpr;
    class Type;
    class UnaryExpr;
    class VarStmt;
    class VarStmtItem;
    class VarStmtItemList;
    class AST
    {
    public:
        virtual ~AST() {}
    };
    class ArgB : public AST
    {
    public:
        virtual ~ArgB() {}
        virtual void accept(ArgBVisitor *v) = 0;
    };
    class DeclB : public AST
    {
    public:
        virtual ~DeclB() {}
        virtual void accept(DeclBVisitor *v) = 0;
    };
    class ExprB : public AST
    {
    public:
        virtual ~ExprB() {}
        virtual void accept(ExprBVisitor *v) = 0;
    };
    class PListB : public AST
    {
    public:
        virtual ~PListB() {}
        virtual void accept(PListBVisitor *v) = 0;
    };
    class StmtB : public AST
    {
    public:
        virtual ~StmtB() {}
        virtual void accept(StmtBVisitor *v) = 0;
    };
    class TypeB : public AST
    {
    public:
        virtual ~TypeB() {}
        virtual void accept(TypeBVisitor *v) = 0;
    };
    class VStmtIB : public AST
    {
    public:
        virtual ~VStmtIB() {}
        virtual void accept(VStmtIBVisitor *v) = 0;
    };
    class AdditionExpr : public ExprB
    {
    public:
        AdditionExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class Arg : public ArgB
    {
    public:
        Arg(std::unique_ptr<ExprB> expr);
        enum class Form
        {
            A,
        };
        std::unique_ptr<ExprB> expr;
        Form form;
        virtual void accept(ArgBVisitor *v);
    };
    class ArgList : public ArgB
    {
    public:
        ArgList(std::unique_ptr<ArgB> arglist, Token comma, std::unique_ptr<ArgB> arg);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ArgB> arglist;
        Token comma;
        std::unique_ptr<ArgB> arg;
        Form form;
        virtual void accept(ArgBVisitor *v);
    };
    class AssignmentExpr : public ExprB
    {
    public:
        AssignmentExpr(std::unique_ptr<ExprB> target, Token equal, std::unique_ptr<ExprB> value);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> target;
        Token equal;
        std::unique_ptr<ExprB> value;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BinandExpr : public ExprB
    {
    public:
        BinandExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BinnotExpr : public ExprB
    {
    public:
        BinnotExpr(Token op, std::unique_ptr<ExprB> operand);
        enum class Form
        {
            TA,
        };
        Token op;
        std::unique_ptr<ExprB> operand;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BinorExpr : public ExprB
    {
    public:
        BinorExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BitandExpr : public ExprB
    {
    public:
        BitandExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BitorExpr : public ExprB
    {
    public:
        BitorExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BitshiftExpr : public ExprB
    {
    public:
        BitshiftExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class BitxorExpr : public ExprB
    {
    public:
        BitxorExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class Block : public StmtB
    {
    public:
        Block(Token ocurb, std::unique_ptr<StmtB> stmts, Token ccurb);
        Block(Token ocurb, Token ccurb);
        enum class Form
        {
            TAT,
            TT,
        };
        Token ocurb;
        std::unique_ptr<StmtB> stmts;
        Token ccurb;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class BuiltinType : public TypeB
    {
    public:
        BuiltinType(Token type);
        enum class Form
        {
            T,
        };
        Token type;
        Form form;
        virtual void accept(TypeBVisitor *v);
    };
    class CallExpr : public ExprB
    {
    public:
        CallExpr(std::unique_ptr<ExprB> callee, Token oparn, std::unique_ptr<ArgB> args, Token cparn);
        CallExpr(std::unique_ptr<ExprB> callee, Token oparn, Token cparn);
        enum class Form
        {
            ATAT,
            ATT,
        };
        std::unique_ptr<ExprB> callee;
        Token oparn;
        std::unique_ptr<ArgB> args;
        Token cparn;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class CompeqExpr : public ExprB
    {
    public:
        CompeqExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class ComplgtExpr : public ExprB
    {
    public:
        ComplgtExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class Decl : public DeclB
    {
    public:
        enum class Form
        {
        };
        Form form;
        virtual void accept(DeclBVisitor *v);
    };
    class DeclList : public DeclB
    {
    public:
        DeclList(std::unique_ptr<DeclB> decllist, std::unique_ptr<DeclB> decl);
        enum class Form
        {
            AA,
        };
        std::unique_ptr<DeclB> decllist;
        std::unique_ptr<DeclB> decl;
        Form form;
        virtual void accept(DeclBVisitor *v);
    };
    class EmptyStmt : public StmtB
    {
    public:
        EmptyStmt(Token semi);
        enum class Form
        {
            T,
        };
        Token semi;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class Expr : public ExprB
    {
    public:
        enum class Form
        {
        };
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class ExprStmt : public StmtB
    {
    public:
        ExprStmt(std::unique_ptr<ExprB> expr, Token semi);
        enum class Form
        {
            AT,
        };
        std::unique_ptr<ExprB> expr;
        Token semi;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class Function : public DeclB
    {
    public:
        Function(Token fun, std::unique_ptr<TypeB> retty, Token name, Token oparn, Token cparn, std::unique_ptr<StmtB> body);
        Function(Token fun, std::unique_ptr<TypeB> retty, Token name, Token oparn, std::unique_ptr<PListB> paramlist, Token cparn, std::unique_ptr<StmtB> body);
        enum class Form
        {
            TATTTA,
            TATTATA,
        };
        Token fun;
        std::unique_ptr<TypeB> retty;
        Token name;
        Token oparn;
        Token cparn;
        std::unique_ptr<StmtB> body;
        std::unique_ptr<PListB> paramlist;
        Form form;
        virtual void accept(DeclBVisitor *v);
    };
    class MultExpr : public ExprB
    {
    public:
        MultExpr(std::unique_ptr<ExprB> lhs, Token op, std::unique_ptr<ExprB> rhs);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<ExprB> lhs;
        Token op;
        std::unique_ptr<ExprB> rhs;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class Param : public PListB
    {
    public:
        Param(std::unique_ptr<TypeB> type, Token name);
        enum class Form
        {
            AT,
        };
        std::unique_ptr<TypeB> type;
        Token name;
        Form form;
        virtual void accept(PListBVisitor *v);
    };
    class ParamList : public PListB
    {
    public:
        ParamList(std::unique_ptr<PListB> paramlist, Token comma, std::unique_ptr<PListB> param);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<PListB> paramlist;
        Token comma;
        std::unique_ptr<PListB> param;
        Form form;
        virtual void accept(PListBVisitor *v);
    };
    class PrimaryExpr : public ExprB
    {
    public:
        PrimaryExpr(Token value);
        PrimaryExpr(Token oparn, std::unique_ptr<ExprB> expr, Token cparn);
        enum class Form
        {
            T,
            TAT,
        };
        Token value;
        Token oparn;
        std::unique_ptr<ExprB> expr;
        Token cparn;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class RetStmt : public StmtB
    {
    public:
        RetStmt(Token ret, std::unique_ptr<ExprB> expr, Token semi);
        enum class Form
        {
            TAT,
        };
        Token ret;
        std::unique_ptr<ExprB> expr;
        Token semi;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class Stmt : public StmtB
    {
    public:
        enum class Form
        {
        };
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class StmtList : public StmtB
    {
    public:
        StmtList(std::unique_ptr<StmtB> stmtlist, std::unique_ptr<StmtB> stmt);
        enum class Form
        {
            AA,
        };
        std::unique_ptr<StmtB> stmtlist;
        std::unique_ptr<StmtB> stmt;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class TernaryExpr : public ExprB
    {
    public:
        TernaryExpr(std::unique_ptr<ExprB> cond, Token quest, std::unique_ptr<ExprB> trues, Token colon, std::unique_ptr<ExprB> falses);
        enum class Form
        {
            ATATA,
        };
        std::unique_ptr<ExprB> cond;
        Token quest;
        std::unique_ptr<ExprB> trues;
        Token colon;
        std::unique_ptr<ExprB> falses;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class Type : public TypeB
    {
    public:
        enum class Form
        {
        };
        Form form;
        virtual void accept(TypeBVisitor *v);
    };
    class UnaryExpr : public ExprB
    {
    public:
        UnaryExpr(Token op, std::unique_ptr<ExprB> operand);
        enum class Form
        {
            TA,
        };
        Token op;
        std::unique_ptr<ExprB> operand;
        Form form;
        virtual void accept(ExprBVisitor *v);
    };
    class VarStmt : public StmtB
    {
    public:
        VarStmt(Token var, std::unique_ptr<TypeB> type, std::unique_ptr<VStmtIB> assignments, Token semi);
        enum class Form
        {
            TAAT,
        };
        Token var;
        std::unique_ptr<TypeB> type;
        std::unique_ptr<VStmtIB> assignments;
        Token semi;
        Form form;
        virtual void accept(StmtBVisitor *v);
    };
    class VarStmtItem : public VStmtIB
    {
    public:
        VarStmtItem(Token name, Token equal, std::unique_ptr<ExprB> expr);
        VarStmtItem(Token name);
        enum class Form
        {
            TTA,
            T,
        };
        Token name;
        Token equal;
        std::unique_ptr<ExprB> expr;
        Form form;
        virtual void accept(VStmtIBVisitor *v);
    };
    class VarStmtItemList : public VStmtIB
    {
    public:
        VarStmtItemList(std::unique_ptr<VStmtIB> varstmtitemlist, Token comma, std::unique_ptr<VStmtIB> varstmtitem);
        enum class Form
        {
            ATA,
        };
        std::unique_ptr<VStmtIB> varstmtitemlist;
        Token comma;
        std::unique_ptr<VStmtIB> varstmtitem;
        Form form;
        virtual void accept(VStmtIBVisitor *v);
    };
// This code was autogenerated - see the utils/ directory

// ASTHEADER END
}
