#pragma once

#include <memory>
#include <vector>
#include "lex/token.h"
#include "visit/visitor.h"

namespace ASTNS
{
// ASTHEADER START

// The following code was autogenerated - see the utils/ directory
    class AST;
    class add;
    class expr;
    class mult;
    class primary;
    class stmt;
    class unary;
    class AST
    {
    public:
        virtual ~AST() {}
        virtual void accept(ASTVisitor *v) = 0;
    };
    class add : public AST
    {
    public:
        add(std::unique_ptr<AST> lhs, Token op, std::unique_ptr<AST> rhs);
        std::unique_ptr<AST> lhs;
        Token op;
        std::unique_ptr<AST> rhs;
        virtual void accept(ASTVisitor *v);
    };
    class expr : public AST
    {
    public:
        expr(std::unique_ptr<AST> expr);
        std::unique_ptr<AST> expr;
        virtual void accept(ASTVisitor *v);
    };
    class mult : public AST
    {
    public:
        mult(std::unique_ptr<AST> lhs, Token op, std::unique_ptr<AST> rhs);
        std::unique_ptr<AST> lhs;
        Token op;
        std::unique_ptr<AST> rhs;
        virtual void accept(ASTVisitor *v);
    };
    class primary : public AST
    {
    public:
        primary(Token value);
        primary(Token oparn, std::unique_ptr<AST> expr, Token cparn);
        Token value;
        Token oparn;
        std::unique_ptr<AST> expr;
        Token cparn;
        virtual void accept(ASTVisitor *v);
    };
    class stmt : public AST
    {
    public:
        stmt(std::unique_ptr<AST> expr);
        std::unique_ptr<AST> expr;
        virtual void accept(ASTVisitor *v);
    };
    class unary : public AST
    {
    public:
        unary(Token op, std::unique_ptr<AST> operand);
        Token op;
        std::unique_ptr<AST> operand;
        virtual void accept(ASTVisitor *v);
    };
// This code was autogenerated - see the utils/ directory

// ASTHEADER END
    // old things {{{
    class AST; // TODO: remove this: this is just to silence the errors coming from the missing AST classes
    class Expr;
    class Decl;
    class Type;
    class Stmt;
    class Program;
    class BinaryExpr;
    class TernaryExpr;
    class UnaryExpr;
    class PrimaryExpr;
    class CallExpr;
    class BlockStmt;
    class ExprStmt;
    class ReturnStmt;
    class VarStmt;
    class BaseType;
    class FunctionDecl;
    class GlobalVarDecl;
    class Param;
    class Arg;
    class Expr : public AST
    {
    public:
        virtual ~Expr() {}
    };
    class Decl : public AST
    {
    public:
        virtual ~Decl() {}
    };
    class Type : public AST
    {
    public:
        virtual ~Type() {}
    };
    class Stmt : public AST
    {
    public:
        virtual ~Stmt() {}
    };
    class Program : public AST
    {
    public:
        Program(std::vector<std::unique_ptr<Decl>> &decls);
        std::vector<std::unique_ptr<Decl>> decls;
        virtual ~Program() {}
    };
    class BinaryExpr : public Expr
    {
    public:
        BinaryExpr(std::unique_ptr<Expr> lhs, std::unique_ptr<Expr> rhs, Token op);
        std::unique_ptr<Expr> lhs;
        std::unique_ptr<Expr> rhs;
        Token op;
    };
    class TernaryExpr : public Expr
    {
    public:
        TernaryExpr(std::unique_ptr<Expr> condition, std::unique_ptr<Expr> trues, std::unique_ptr<Expr> falses);
        std::unique_ptr<Expr> condition;
        std::unique_ptr<Expr> trues;
        std::unique_ptr<Expr> falses;
    };
    class UnaryExpr : public Expr
    {
    public:
        UnaryExpr(std::unique_ptr<Expr> operand, Token op);
        std::unique_ptr<Expr> operand;
        Token op;
    };
    class PrimaryExpr : public Expr
    {
    public:
        PrimaryExpr(Token value);
        Token value;
    };
    class CallExpr : public Expr
    {
    public:
        CallExpr(std::unique_ptr<Expr> func, std::unique_ptr<Arg> args);
        std::unique_ptr<Expr> func;
        std::unique_ptr<Arg> args;
    };
    class BlockStmt : public Stmt
    {
    public:
        BlockStmt(std::vector<std::unique_ptr<Stmt>> &stmts);
        std::vector<std::unique_ptr<Stmt>> stmts;
    };
    class ExprStmt : public Stmt
    {
    public:
        ExprStmt(std::unique_ptr<Expr> expr);
        std::unique_ptr<Expr> expr;
    };
    class ReturnStmt : public Stmt
    {
    public:
        ReturnStmt(std::unique_ptr<Expr> val);
        std::unique_ptr<Expr> val;
    };
    class VarStmt : public Stmt
    {
    public:
        VarStmt(std::unique_ptr<Type> type, std::vector<std::unique_ptr<Expr>> &assignments);
        std::unique_ptr<Type> type;
        std::vector<std::unique_ptr<Expr>> assignments;
    };
    class BaseType : public Type
    {
    public:
        BaseType(Token type);
        Token type;
    };
    class FunctionDecl : public Decl
    {
    public:
        FunctionDecl(std::unique_ptr<Type> rettype, Token name, std::unique_ptr<Param> params, std::unique_ptr<BlockStmt> block);
        std::unique_ptr<Type> rettype;
        Token name;
        std::unique_ptr<Param> params;
        std::unique_ptr<BlockStmt> block;
    };
    class GlobalVarDecl : public Decl
    {
    public:
        GlobalVarDecl(std::unique_ptr<Type> type, std::vector<std::unique_ptr<Expr>> &assignments);
        std::unique_ptr<Type> type;
        std::vector<std::unique_ptr<Expr>> assignments;
    };
    class Param : public AST
    {
    public:
        Param(std::unique_ptr<Type> type, Token name, std::unique_ptr<Param> next);
        std::unique_ptr<Type> type;
        Token name;
        std::unique_ptr<Param> next;
        virtual ~Param() {}
    };
    class Arg : public AST
    {
    public:
        Arg(std::unique_ptr<Expr> value, std::unique_ptr<Arg> next);
        std::unique_ptr<Expr> value;
        std::unique_ptr<Arg> next;
        virtual ~Arg() {}
    };
    // }}}
}
