#pragma once

#include "ir/instruction.h"
#include "ir/visitor.h"
#include "llvm/Support/raw_ostream.h"

namespace IR {
    class CFGDotter : public BrVisitor {
    public:
        CFGDotter(llvm::raw_ostream &ostream);

        // CFG DOT METHOD START
// The following code was autogenerated - see the utils/ directory
void visitReturn(IR::Instrs::Return *i) override;
void visitGotoBr(IR::Instrs::GotoBr *i) override;
void visitCondBr(IR::Instrs::CondBr *i) override;
// This code was autogenerated - see the utils/ directory
        // CFG DOT METHOD END
    private:
        llvm::raw_ostream &ostream;
    };
}
