
// The following code was autogenerated - see the utils/ directory
#include "parse/ast.h"
ASTNS::Add::Add(std::unique_ptr<AST> lhs, Token op, std::unique_ptr<AST> rhs): lhs(std::move(lhs)), op(op), rhs(std::move(rhs)) {}
void ASTNS::Add::accept(ASTVisitor *v) { v->visitAdd(this); }
ASTNS::Mult::Mult(std::unique_ptr<AST> lhs, Token op, std::unique_ptr<AST> rhs): lhs(std::move(lhs)), op(op), rhs(std::move(rhs)) {}
void ASTNS::Mult::accept(ASTVisitor *v) { v->visitMult(this); }
ASTNS::New_expr::New_expr(std::unique_ptr<AST> expr): expr(std::move(expr)) {}
void ASTNS::New_expr::accept(ASTVisitor *v) { v->visitNew_expr(this); }
ASTNS::New_stmt::New_stmt(std::unique_ptr<AST> expr): expr(std::move(expr)) {}
void ASTNS::New_stmt::accept(ASTVisitor *v) { v->visitNew_stmt(this); }
ASTNS::Primary::Primary(Token value): value(value) {}
ASTNS::Primary::Primary(Token oparn, std::unique_ptr<AST> expr, Token cparn): oparn(oparn), expr(std::move(expr)), cparn(cparn) {}
void ASTNS::Primary::accept(ASTVisitor *v) { v->visitPrimary(this); }
ASTNS::Unary::Unary(Token op, std::unique_ptr<AST> operand): op(op), operand(std::move(operand)) {}
void ASTNS::Unary::accept(ASTVisitor *v) { v->visitUnary(this); }
// This code was autogenerated - see the utils/ directory

