#pragma once

namespace ASTNS
{
// ASTFORWDECL BEGIN

// The following code was autogenerated - see the utils/ directory
class AST;
class add;
class expr;
class mult;
class primary;
class stmt;
class unary;
// This code was autogenerated - see the utils/ directory

// ASTFORWDECL END
}

class ASTVisitor
{

};
