keywords = [
    ('FLOAT', 'FLOAT'),
    ('TRUE', 'TRUE'),
    ('FALSE', 'FALSE'),
    ('NULL_', 'NULL_'),
    ('PRINT', 'PRINT'),
    ('VOID', 'VOID'),
    ('NAMESPACE', 'NAMESPACE'),
    ('CLASS', 'CLASS'),
    ('ENUM', 'ENUM'),
    ('RETURN', 'RETURN'),
    ('THIS', 'THIS'),
    ('WHILE', 'WHILE'),
    ('FOR', 'FOR'),
    ('IF', 'IF'),
    ('ELSE', 'ELSE'),
    ('SWITCH', 'SWITCH'),
    ('CASE', 'CASE'),
    ('DEFAULT', 'DEFAULT'),
    ('BREAK', 'BREAK'),
    ('BREAKALL', 'BREAKALL'),
    ('BREAKTO', 'BREAKTO'),
    ('CONST', 'CONST'),
    ('CONTINUE', 'CONTINUE'),
    ('INLINE', 'INLINE'),
    ('VOLATILE', 'VOLATILE'),
]
